POST http://localhost:5073/breakfasts
Content-Type: application/json

{
    "name" : "Vegan Sunshine",
    "description" : "Vegan everything! Join us for a ",
    "startDateTime" : "2022-04-08T08:00:00",
    "endDateTime" : "2022-04-08T11:00:00",
    "savory" :[
        "Oatmeal",
        "Avaocado Toast",
        "Omlette",
        "Salad"
    ],
    "Sweet": [
        "Cookie"
    ]
}