@id=3a132127-d31a-49ff-90cd-923400f956fc

PUT http://localhost:5073/breakfasts/{{id}}
Content-Type: application/json

{
    "name" : "Pork Sunshine",
    "description" : "Pork is everything! Join us for a ",
    "startDateTime" : "2022-04-08T08:00:00",
    "endDateTime" : "2022-04-08T11:00:00",
    "savory" :[
        "Oatmeal",
        "Avaocado Toast",
        "Omlette",
        "Salad"
    ],
    "Sweet": [
        "Cookie"
    ]
}